In [1]:
import numpy as np
import math

In [5]:
test = np.random.randint(0, 10, size=(3, 3))
b = np.random.randint(0, 10, size=(3, 3))

print(a, a.shape, '\n')
print(b, b.shape, '\n')

dist = np.zeros((b.shape[0], a.shape[0]))

for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        dist[i, j] = np.linalg.norm(a[i] - b[j])

# print(dist, end='\n\n\n')


[[3 5 7]
 [0 3 2]
 [0 6 7]] (3, 3) 

[[0 0 8]
 [7 4 4]
 [8 1 8]] (3, 3) 



### Three loop

In [4]:
for i in range(a.shape[0]):
    dist[i, :] = np.linalg.norm(a[i] - b, axis=1)

print(dist, end='\n\n\n')

[[6.         7.81024968]
 [5.         4.24264069]]




In [6]:
dist1 = np.zeros(shape=(1, 2))
dist1[0, :] = np.linalg.norm(a[0] - b, axis=1)
dist1

array([[6.        , 7.81024968]])

In [7]:
print(a[0], b[0])

[7 2] [1 2]


In [8]:
a[0] - b

array([[ 6,  0],
       [ 5, -6]])

In [9]:
np.sqrt(np.sum([7**2, 7**2, 4**2, 3**2, 0**2]))

11.090536506409418