In [1]:
import numpy as np
import math
import scipy as sp

In [107]:
test = np.random.randint(0, 10, size=(4, 4))
train = np.random.randint(0, 10, size=(4, 4))

print('test', '\n', test, test.shape, '\n')
print('train', '\n', train, train.shape, '\n')

test 
 [[6 1 8 2]
 [5 0 7 4]
 [2 5 7 2]
 [7 4 3 8]] (4, 4) 

train 
 [[7 9 1 8]
 [8 5 4 2]
 [7 4 8 4]
 [2 7 8 6]] (4, 4) 



### Three loop
$
    dist_{ij} = \sqrt{\sum_{k=1}^{d}(X_{mk} - Y_{nk})^2} | 
    dist_{ij} = \sqrt{\sum_{k=1}^{d}(test_{mk} - train_{nk})^2}
$


In [108]:
def dist_3l(test, train):
    # m->i, n->j, d->k
    m, d = test.shape
    n, d = train.shape
    # print(test.shape, i, k)
    # print(train.shape,j, k)

    dists = np.zeros((m, n))

    for i in range(m):
        for j in range(n):
            val = 0
            for k in range(d):
                val += (test[i][k] - train[j][k])**2
            dists[i][j] = np.sqrt(val)
    
    return dists

def dist_2l(test, train):
    # m->i, n->j, d->k
    m, d = test.shape
    n, d = train.shape
    # print(test.shape, i, k)
    # print(train.shape,j, k)

    dists = np.zeros((m, n))

    for i in range(m):
        for j in range(n):
            dists[i, j] = np.sqrt(np.sum(np.square(test[i] - train[j])))

    return dists

def dist_1l(test, train):
    # m->i, n->j, d->k
    m, d = test.shape
    n, d = train.shape
    # print(test.shape, i, k)
    # print(train.shape,j, k)

    dists = np.zeros((m, n))

    for i in range(m):
        dists[i, :] = np.sqrt(np.sum(np.square(test[i] - train), axis=1))

    return dists

def dist_0l(test, train):
    # m->i, n->j, d->k
    m, d = test.shape
    n, d = train.shape
    # print(test.shape, i, k)
    # print(train.shape,j, k)

    dists = np.zeros((m, n))

    dists = np.sqrt(np.sum(np.square(test), axis=1).reshape(-1, 1)
     - 2*np.dot(test, train.T)
      + np.sum(np.square(train), axis=1))

    return dists

def predict_labels(dists, k, y_label):
    pass




SyntaxError: incomplete input (1840496215.py, line 65)

In [109]:
dists = dist_3l(test, train)
dists

array([[12.24744871,  6.        ,  3.74165739,  8.24621125],
       [11.70469991,  6.8556546 ,  4.58257569,  7.93725393],
       [10.63014581,  6.70820393,  5.56776436,  4.58257569],
       [ 5.38516481,  6.244998  ,  6.40312424,  7.93725393]])

In [110]:
dists = dist_2l(test, train)
dists

array([[12.24744871,  6.        ,  3.74165739,  8.24621125],
       [11.70469991,  6.8556546 ,  4.58257569,  7.93725393],
       [10.63014581,  6.70820393,  5.56776436,  4.58257569],
       [ 5.38516481,  6.244998  ,  6.40312424,  7.93725393]])

In [111]:
dists = dist_1l(test, train)
dists

array([[12.24744871,  6.        ,  3.74165739,  8.24621125],
       [11.70469991,  6.8556546 ,  4.58257569,  7.93725393],
       [10.63014581,  6.70820393,  5.56776436,  4.58257569],
       [ 5.38516481,  6.244998  ,  6.40312424,  7.93725393]])

In [112]:
dists = dist_0l(test, train)
dists

array([[12.24744871,  6.        ,  3.74165739,  8.24621125],
       [11.70469991,  6.8556546 ,  4.58257569,  7.93725393],
       [10.63014581,  6.70820393,  5.56776436,  4.58257569],
       [ 5.38516481,  6.244998  ,  6.40312424,  7.93725393]])

In [113]:
print(test, end='\n\n')
print(train, end='\n\n')

[[6 1 8 2]
 [5 0 7 4]
 [2 5 7 2]
 [7 4 3 8]]

[[7 9 1 8]
 [8 5 4 2]
 [7 4 8 4]
 [2 7 8 6]]



In [145]:
t = np.random.randint(0, 5, (20,))
print(t)
counts = np.bincount(t)
print(counts)
np.argmax(counts)

[0 4 1 1 3 0 4 4 0 2 4 2 3 0 2 1 2 2 3 2]
[4 3 6 3 4]


2

In [151]:
unique, unique_counts = np.unique(t, return_counts=True)
print(unique, unique_counts)
arg_max = np.argmax(unique_counts)
print(unique[arg_max])

[0 1 2 3 4] [4 3 6 3 4]
2
