In [11]:
from scipy.stats import laplace
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets

In [7]:
dataset = datasets.load_iris()

In [8]:
ext_target = dataset.target[:, None]
pd.DataFrame(
    np.concatenate((dataset.data, ext_target, dataset.target_names[ext_target]), axis=1),
    columns=dataset.feature_names + ['target label', 'target name'])

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)  \
0                 5.1              3.5               1.4              0.2   
1                 4.9              3.0               1.4              0.2   
2                 4.7              3.2               1.3              0.2   
3                 4.6              3.1               1.5              0.2   
4                 5.0              3.6               1.4              0.2   
..                ...              ...               ...              ...   
145               6.7              3.0               5.2              2.3   
146               6.3              2.5               5.0              1.9   
147               6.5              3.0               5.2              2.0   
148               6.2              3.4               5.4              2.3   
149               5.9              3.0               5.1              1.8   

    target label target name  
0              0      setosa  
1              0      setosa  
2              0      setosa  
3              0      setosa  
4              0      setosa  
..           ...         ...  
145            2   virginica  
146            2   virginica  
147            2   virginica  
148            2   virginica  
149            2   virginica  

[150 rows x 6 columns]

In [10]:
features = dataset.data
targets = dataset.target

In [17]:
features.shape, targets.shape

((150, 4), (150,))

In [4]:
# Laplace distribution
class LaplaceDistribution:
    def __init__(self, features):
        self.loc = np.mean(features, axis=0)
        self.scale = np.std(features, axis=0)**2

    def logpdf(self, features):
        return -np.log(2*self.scale) - (np.abs(features - self.loc)) / self.scale

    def pdf(self, features):
        return np.exp(self.logpdf(features))




In [25]:
test1 = laplace(loc=features[:, :4].mean(axis=0), scale=features[:,:4].std(axis=0)**2)
print(test1.logpdf(features[:2,:4]))

test2 = LaplaceDistribution(features[:,:4]).logpdf(features[:2,:4])
print(test2)

assert np.allclose(test1.logpdf(features[:2,:4]), test2)
print('Seems fine!')


[[-1.40046986 -1.37133372 -2.58484776 -1.87501251]
 [-1.69410292  0.67056885 -2.58484776 -1.87501251]]
[[-1.40046986 -1.37133372 -2.58484776 -1.87501251]
 [-1.69410292  0.67056885 -2.58484776 -1.87501251]]
Seems fine!
